#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysAllowUploads", {PERSISTENT, BOOL, "0", std::nullopt, 0, SETTINGS_SIMPLE}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarGpsAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUserReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"DriverLockoutCount", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, INT, "0"}},
    {"EcuDisableFailed", {CLEAR_ON_MANAGER_START, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT, BOOL}},
    {"ExperimentalLongitudinalEnabled", {PERSISTENT, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"PersistChillState", {PERSISTENT, BOOL, "0", "0", 1}},
    {"PersistExperimentalState", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"PersistedCCStatus", {PERSISTENT, INT, "0", "0"}},
    {"PersistedCEStatus", {PERSISTENT, INT, "0", "0"}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1", std::nullopt, 0, SETTINGS_SIMPLE}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    // Internal kill switch; the platform verification allowlist remains the hard safety gate.
    {"HondaBoschARadar", {PERSISTENT, BOOL, "1"}},
    {"HondaGasFactorParams", {PERSISTENT, FLOAT}},
    {"HondaLateralPidKiScale", {PERSISTENT, FLOAT, "1.0", "1.0", 3}},
    {"HondaLateralPidKpScale", {PERSISTENT, FLOAT, "1.0", "1.0", 3}},
    {"HondaWindFactorParams", {PERSISTENT, FLOAT}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsLiveStreaming", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRHD", {PERSISTENT, BOOL, std::nullopt, std::nullopt, 0, SETTINGS_SIMPLE}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsRHDOverride", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "main_en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LivestreamEncoderBitrate", {CLEAR_ON_MANAGER_START | DONT_LOG, INT}},
    {"LivestreamRequestKeyframe", {CLEAR_ON_MANAGER_START | DONT_LOG, BOOL}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"PriusClusterOffsetMigrated", {PERSISTENT, BOOL, "0", "0"}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SentryModeEnabled", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"SentryModeCapture", {CLEAR_ON_MANAGER_START, BOOL}},
    {"SentryModeLastEvent", {PERSISTENT, JSON, "{}", "{}"}},
    {"SentryModeNtfyUrl", {PERSISTENT, STRING}},
    {"SentryModeSensitivity", {PERSISTENT, FLOAT, "0.04", "0.04", 0, SETTINGS_SIMPLE}},
    {"SentryModeStatus", {CLEAR_ON_MANAGER_START | DONT_LOG, JSON}},
    {"SentryModeWarningTime", {PERSISTENT, FLOAT, "1.0", "1.0", 0, SETTINGS_SIMPLE}},
    {"SentryModeWebhook", {PERSISTENT, STRING}},
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"ShowAllToggles", {PERSISTENT, BOOL, "0", "0", 3}},
    {"UsePrebuilt", {PERSISTENT, BOOL, "1"}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UsbGpuActive", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"UsbGpuCompiled", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"UsbGpuLoading", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"UsbGpuPresent", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"Version", {PERSISTENT, STRING}},

    // StarPilot variables
    {"AccelerationPath", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"AccelerationProfile", {PERSISTENT, INT, "0", "0", 0, SETTINGS_SIMPLE}},
    {"AdjacentLeadsUI", {PERSISTENT, BOOL, "1", "0", 3}},
    {"AdjacentPath", {PERSISTENT, BOOL, "0", "0", 3, SETTINGS_SIMPLE}},
    {"AdjacentPathMetrics", {PERSISTENT, BOOL, "0", "0", 3}},
    {"AdvancedCustomUI", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"AdvancedLateralTune", {PERSISTENT, BOOL, "1", "0", 2}},
    {"AdvancedLongitudinalTune", {PERSISTENT, BOOL, "1", "0", 3}},
    {"AggressiveFollow", {PERSISTENT, FLOAT, "1.25", "1.25", 2}},
    {"AggressiveFollowHigh", {PERSISTENT, FLOAT, "1.0", "1.0", 2}},
    {"AggressiveJerkAcceleration", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AggressiveJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"AggressiveJerkDeceleration", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AggressiveJerkSpeed", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AggressiveJerkSpeedDecrease", {PERSISTENT, FLOAT, "50.0", "50.0", 3}},
    {"AlertVolumeControl", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"AllowImpossibleAcceleration", {PERSISTENT, BOOL, "0", "0", 3}},
    {"AlwaysOnLateral", {PERSISTENT, BOOL, "1", "0", 0, SETTINGS_SIMPLE}},
    {"AlwaysOnLateralLKAS", {PERSISTENT, BOOL, "1", "0", 2}},
    {"ApiCache_DriveStats", {PERSISTENT, JSON, "{}", "{}"}},
    {"AutomaticallyDownloadModels", {PERSISTENT, BOOL, "1", "0", 1}},
    {"AutomaticUpdates", {PERSISTENT, BOOL, "1", "1", 0}},
    {"AllowGpuModelDownloadWithoutGpu", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"AvailableModelNames", {PERSISTENT, STRING, "", "", 1}},
    {"AvailableModelSeries", {PERSISTENT, STRING, "", "", 1}},
    {"AvailableModels", {PERSISTENT, STRING, "", "", 1}},
    {"AvailableModelArtifactFormats", {PERSISTENT, STRING, "", "", 1}},
    {"BlacklistedModels", {PERSISTENT, STRING, "", "", 2}},
    {"BootLogo", {PERSISTENT, STRING, "starpilot", "stock", 0}},
    {"BuildMetadata", {PERSISTENT, STRING, "", "", 0}},
    {"BlindSpotMetrics", {PERSISTENT, BOOL, "1", "0", 3}},
    {"BlindSpotPath", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"BelowSteerSpeedVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"BorderMetrics", {PERSISTENT, BOOL, "0", "0", 3}},
    {"BorderWidth", {PERSISTENT, FLOAT, "100.0", "100.0", 2, SETTINGS_SIMPLE}},
    {"CalibratedLateralAcceleration", {PERSISTENT, FLOAT, "2.0", "2.0", 2}},
    {"CalibrationProgress", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"CameraOffset", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"CameraView", {PERSISTENT, INT, "2", "0", 2, SETTINGS_SIMPLE}},
    {"CancelDownloadMaps", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"DisableWideRoad", {PERSISTENT, BOOL, "0", "0", 3}},
    {"CancelModelDownload", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"CancelThemeDownload", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"CarMake", {PERSISTENT, STRING, "mock", "mock", 0, SETTINGS_SIMPLE}},
    {"CarModel", {PERSISTENT, STRING, "MOCK", "MOCK", 0, SETTINGS_SIMPLE}},
    {"CarModelName", {PERSISTENT, STRING, "", "", 0}},
    {"CECurves", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"CECurvesLead", {PERSISTENT, BOOL, "0", "0", 1}},
    {"CELead", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"CEModelStopTime", {PERSISTENT, FLOAT, "7.7", "0.0", 2, SETTINGS_SIMPLE}},
    {"CEOpenRoad", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"CESignalLaneDetection", {PERSISTENT, BOOL, "1", "0", 2}},
    {"CESignalSpeed", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"CESlowerLead", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"CESpeed", {PERSISTENT, FLOAT, "0.0", "0.0", 1, SETTINGS_SIMPLE}},
    {"CESpeedLead", {PERSISTENT, FLOAT, "0.0", "0.0", 1, SETTINGS_SIMPLE}},
    {"CCMLead", {PERSISTENT, BOOL, "1", "0", 1}},
    {"CCMLaunchAssist", {PERSISTENT, BOOL, "0", "0", 1}},
    {"CCMSetSpeedMargin", {PERSISTENT, FLOAT, "3.0", "0.0", 1}},
    {"CCMSpeed", {PERSISTENT, FLOAT, "45.0", "0.0", 1}},
    {"CCMSpeedLead", {PERSISTENT, FLOAT, "35.0", "0.0", 1}},
    {"CCStatus", {CLEAR_ON_OFFROAD_TRANSITION, INT, "0", "0"}},
    {"CEStatus", {CLEAR_ON_OFFROAD_TRANSITION, INT, "0", "0"}},
    {"CEStopLights", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"CEStoppedLead", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"ClusterOffset", {PERSISTENT, FLOAT, "1.0", "1.0", 2, SETTINGS_SIMPLE}},
    {"ColorScheme", {PERSISTENT, STRING, "stock", "stock", 0}},
    {"ColorToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"BootLogoToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"Compass", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"CommunityFavorites", {PERSISTENT, STRING, "", "", 1}},
    {"ConditionalChill", {PERSISTENT, BOOL, "0", "0", 1}},
    {"ConditionalExperimental", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"CurvatureData", {PERSISTENT | DONT_LOG, JSON, "{}", "{}"}},
    {"CurveSpeedController", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"CurveSpeedControllerNoLead", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"CustomAlerts", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"CustomAccelProfile", {PERSISTENT, BOOL, "0", "0", 3}},
    {"CustomAccelProfileInitialized", {PERSISTENT, BOOL, "0", "0", 3}},
    {"CustomAccelProfile0MPH", {PERSISTENT, FLOAT, "3.0", "3.0", 3}},
    {"CustomAccelProfile11MPH", {PERSISTENT, FLOAT, "2.5", "2.5", 3}},
    {"CustomAccelProfile22MPH", {PERSISTENT, FLOAT, "2.0", "2.0", 3}},
    {"CustomAccelProfile34MPH", {PERSISTENT, FLOAT, "1.5", "1.5", 3}},
    {"CustomAccelProfile45MPH", {PERSISTENT, FLOAT, "1.0", "1.0", 3}},
    {"CustomAccelProfile56MPH", {PERSISTENT, FLOAT, "0.8", "0.8", 3}},
    {"CustomAccelProfile89MPH", {PERSISTENT, FLOAT, "0.6", "0.6", 3}},
    {"CustomCruise", {PERSISTENT, FLOAT, "1.0", "1.0", 2, SETTINGS_SIMPLE}},
    {"CustomCruiseLong", {PERSISTENT, FLOAT, "5.0", "5.0", 2, SETTINGS_SIMPLE}},
    {"CustomPersonalities", {PERSISTENT, BOOL, "0", "0", 2}},
    {"CancelButtonControl", {PERSISTENT, INT, "1", "0", 2, SETTINGS_SIMPLE}},
    {"CancelButtonControlsMigrated", {PERSISTENT, BOOL, "0", "0"}},
    {"AOLLKASMigratedToButtonControl", {PERSISTENT, BOOL, "0", "0"}},
    {"TrafficPersonalityProfile", {PERSISTENT, BOOL, "1", "1", 2}},
    {"AggressivePersonalityProfile", {PERSISTENT, BOOL, "1", "1", 2}},
    {"StandardPersonalityProfile", {PERSISTENT, BOOL, "1", "1", 2}},
    {"RelaxedPersonalityProfile", {PERSISTENT, BOOL, "1", "1", 2}},
    {"CustomThemes", {PERSISTENT, BOOL, "0", "0", 0}},
    {"CustomUI", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"DebugMode", {CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0", "0"}},
    {"DecelerationProfile", {PERSISTENT, INT, "1", "0", 2, SETTINGS_SIMPLE}},
    {"DeveloperMetrics", {PERSISTENT, BOOL, "1", "0", 3}},
    {"DeveloperSidebar", {PERSISTENT, BOOL, "1", "0", 3}},
    {"DeveloperSidebarMetric1", {PERSISTENT, INT, "1", "0", 3}},
    {"DeveloperSidebarMetric2", {PERSISTENT, INT, "2", "0", 3}},
    {"DeveloperSidebarMetric3", {PERSISTENT, INT, "3", "0", 3}},
    {"DeveloperSidebarMetric4", {PERSISTENT, INT, "4", "0", 3}},
    {"DeveloperSidebarMetric5", {PERSISTENT, INT, "5", "0", 3}},
    {"DeveloperSidebarMetric6", {PERSISTENT, INT, "6", "0", 3}},
    {"DeveloperSidebarMetric7", {PERSISTENT, INT, "7", "0", 3}},
    {"DeveloperUI", {PERSISTENT, BOOL, "0", "0", 3}},
    {"GalaxyDeveloperMode", {PERSISTENT | DONT_LOG, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"DeveloperWidgets", {PERSISTENT, BOOL, "1", "0", 3}},
    {"DeviceManagement", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"DeviceShutdown", {PERSISTENT, INT, "6", "6", 1, SETTINGS_SIMPLE}},
    {"DisableOnroadUploads", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"DisableOpenpilotLongitudinal", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"DiscordUsername", {PERSISTENT, STRING, "", "", 0}},
    {"DisengageVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"DistanceButtonControl", {PERSISTENT, INT, "1", "0", 2, SETTINGS_SIMPLE}},
    {"DistanceIconPack", {PERSISTENT, STRING, "stock", "stock", 0}},
    {"DistanceIconToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"DownloadableBootLogos", {PERSISTENT, STRING, "", ""}},
    {"DownloadableColors", {PERSISTENT, STRING, "", ""}},
    {"DownloadableDistanceIcons", {PERSISTENT, STRING, "", ""}},
    {"DownloadableIcons", {PERSISTENT, STRING, "", ""}},
    {"DownloadableSignals", {PERSISTENT, STRING, "", ""}},
    {"DownloadableSounds", {PERSISTENT, STRING, "", ""}},
    {"DownloadableWheels", {PERSISTENT, STRING, "", ""}},
    {"DownloadAllModels", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"DownloadMaps", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"DriverCamera", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"Model", {PERSISTENT, STRING, "rdf43", "rdf43", 1}},
    {"ModelVersion", {PERSISTENT, STRING, "v15", "v15", 1}},
    {"DrivingModel", {PERSISTENT, STRING, "rdf43", "rdf43", 1}},
    {"DrivingModelName", {PERSISTENT, STRING, "Regret Driven Framework V4", "Regret Driven Framework V4", 1}},
    {"DrivingModelVersion", {PERSISTENT, STRING, "v15", "v15", 1}},
    {"DynamicPathWidth", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"DynamicPedalsOnUI", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"EngageVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"EVTuning", {PERSISTENT, BOOL, "0", "0", 3}},
    {"Fahrenheit", {PERSISTENT, BOOL, "0", "0", 3}},
    {"FlashPanda", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"GMDashSpoofOffsets", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"GMPedalLongitudinal", {PERSISTENT, BOOL, "1", "1", 2, SETTINGS_SIMPLE}},
    {"HKGRemoteStartBootsComma", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"IgnoreIgnitionLine", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"LongPitch", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"RemoteStartBootsComma", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"RemapCancelToDistance", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"NAPAdaptiveAccel", {PERSISTENT, BOOL, "1", "1", 0, SETTINGS_SIMPLE}},
    {"NAPFollowDistance", {PERSISTENT, INT, "4", "4"}},
    {"NAPForcePreAP", {PERSISTENT, BOOL, "0", "0"}},
    {"NAPPedalEnabled", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"NAPPedalCanBus", {PERSISTENT, INT, "2", "2", 0, SETTINGS_SIMPLE}},
    {"NAPPedalCalibDone", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"NAPPedalCalibMin", {PERSISTENT, FLOAT, "-3.0", "-3.0"}},
    {"NAPPedalCalibMax", {PERSISTENT, FLOAT, "99.6", "99.6"}},
    {"NAPPedalCalibFactor", {PERSISTENT, FLOAT, "1.0", "1.0", 0, SETTINGS_SIMPLE}},
    {"NAPPedalCalibZero", {PERSISTENT, FLOAT, "0.0", "0.0", 0, SETTINGS_SIMPLE}},
    {"NAPPedalProfile", {PERSISTENT, INT, "4", "4"}},
    {"NAPRadarBehindNosecone", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"NAPRadarEnabled", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"NAPRadarOffset", {PERSISTENT, FLOAT, "0.0", "0.0", 0, SETTINGS_SIMPLE}},
    {"ForceAutoTune", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ForceAutoTuneOff", {PERSISTENT, BOOL, "1", "0", 2}},
    {"ForceFingerprint", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ForceOffroad", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"ForceOnroad", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"ForceStops", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"ForceStopDistanceOffset", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ForceStandstill", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"FordLKASButtonControlMigrated", {PERSISTENT, BOOL, "0", "0"}},
    {"ForceTorqueController", {PERSISTENT, BOOL, "0", "0", 3}},
    {"FordAngleBlend", {PERSISTENT, FLOAT, "0.5", "0.5", 2}},
    {"FordAngleHighSpeedDamping", {PERSISTENT, FLOAT, "1.0", "1.0", 2}},
    {"FordAngleHighSpeedFactor", {PERSISTENT, FLOAT, "1.0", "1.0", 2}},
    {"FordAngleLaneChangeFactor", {PERSISTENT, FLOAT, "1.0", "1.0", 2}},
    {"FordAngleLowSpeedFactor", {PERSISTENT, FLOAT, "1.0", "1.0", 2}},
    {"FordCurvatureBlendHigh", {PERSISTENT, FLOAT, "0.4", "0.4", 2}},
    {"FordCurvatureBlendLow", {PERSISTENT, FLOAT, "0.4", "0.4", 2}},
    {"FordCurvatureLaneChangeFactor", {PERSISTENT, FLOAT, "0.85", "0.85", 2}},
    {"FordHandsFreeCluster", {PERSISTENT, BOOL, "0", "0", 2}},
    {"FordHumanTurnDetection", {PERSISTENT, BOOL, "1", "1", 2}},
    {"FordLateralMode", {PERSISTENT, INT, "1", "1", 2}},
    {"FLMActiveOverrides", {PERSISTENT, JSON, "{}", "{}", 2}},
    {"FLMActiveProfileId", {PERSISTENT, STRING, "", "", 2}},
    {"FLMSubmittedTune", {CLEAR_ON_MANAGER_START, JSON, "{}", "{}"}},
    {"FLMTrialBaseline", {PERSISTENT | DONT_LOG, JSON, "{}", "{}"}},
    {"FLMTrialApplied", {PERSISTENT, BOOL, "0", "0", 2}},
    {"FPSCounter", {PERSISTENT, BOOL, "0", "0", 3}},
    {"GalaxyDashboardStats", {PERSISTENT | DONT_LOG, JSON, "{}", "{}"}},
    {"StarPilotApiToken", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"StarPilotCarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES, "", ""}},
    {"StarPilotCarParamsPersistent", {PERSISTENT, BYTES, "", ""}},
    {"StarPilotDongleId", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"StarPilotFavoriteSlots", {PERSISTENT, JSON, "[]", "[]", 1}},
    {"StarPilotStats", {PERSISTENT | DONT_LOG, JSON, "{}", "{}"}},
    {"StarPilotTogglesUpdated", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"GoatScream", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"GoatScreamCriticalAlerts", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"GreenLightAlert", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"HideAlerts", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideChangingLanesBanner", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideDistanceProfileBanner", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideTurningBanner", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideDMIcon", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideLeadMarker", {PERSISTENT, BOOL, "0", "0", 2}},
    {"HideMaxSpeed", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideSpeed", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideSpeedLimit", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HideSteeringWheel", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HigherBitrate", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"HolidayThemes", {PERSISTENT, BOOL, "1", "0", 0, SETTINGS_SIMPLE}},
    {"HumanLaneChanges", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"IconPack", {PERSISTENT, STRING, "stock", "stock", 0}},
    {"IconToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"IncreasedStoppedDistance", {PERSISTENT, FLOAT, "0.0", "0.0", 1, SETTINGS_SIMPLE}},
    {"IncreasedStoppedDistanceLowVisibility", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"IncreasedStoppedDistanceRain", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"IncreasedStoppedDistanceRainStorm", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"IncreasedStoppedDistanceSnow", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"RedneckCruise", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"IncreaseFollowingLowVisibility", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"IncreaseFollowingRain", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"IncreaseFollowingRainStorm", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"IncreaseFollowingSnow", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"IncreaseThermalLimits", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"IssueReported", {CLEAR_ON_MANAGER_START, JSON, "{}", "{}"}},
    {"KonikDongleId", {PERSISTENT, STRING, "", "", 0}},
    {"KonikMinutes", {PERSISTENT, INT, "0", "0", 0}},
    {"LaneCentering", {PERSISTENT, BOOL, "0", "0", 2}},
    {"LaneCenteringPauseOnSignal", {PERSISTENT, BOOL, "1", "1", 2}},
    {"LaneCenteringE2EAuthority", {PERSISTENT, FLOAT, "1.0", "1.0", 3}},
    {"LaneCenterOffset", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"LaneChanges", {PERSISTENT, BOOL, "1", "1", 0, SETTINGS_SIMPLE}},
    {"LaneChangeCloseGap", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"LaneChangeCloseGapSeconds", {PERSISTENT, FLOAT, "0.6", "0.6", 1, SETTINGS_SIMPLE}},
    {"LaneChangeSmoothing", {PERSISTENT, INT, "5", "10", 1, SETTINGS_SIMPLE}},
    {"LaneChangeTime", {PERSISTENT, FLOAT, "1.0", "0.0", 1, SETTINGS_SIMPLE}},
    {"LaneDetectionWidth", {PERSISTENT, FLOAT, "0.0", "0.0", 1, SETTINGS_SIMPLE}},
    {"LaneLinesColor", {PERSISTENT, STRING, "", "", 2, SETTINGS_SIMPLE}},
    {"LaneLinesWidth", {PERSISTENT, FLOAT, "4.0", "2.0", 2, SETTINGS_SIMPLE}},
    {"LastMapsUpdate", {PERSISTENT, STRING, "", ""}},
    {"MapsDownloadProgress", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"MapsDownloadSizeCache", {PERSISTENT, STRING, "{}", "{}"}},
    {"LateralTune", {PERSISTENT, BOOL, "1", "0", 1}},
    {"LeadDepartingAlert", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"LeadDetectionThreshold", {PERSISTENT, INT, "35", "50", 3}},
    {"LeadIndicator", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"LeadInfo", {PERSISTENT, BOOL, "1", "0", 3}},
    {"LKASButtonControl", {PERSISTENT, INT, "5", "0", 2, SETTINGS_SIMPLE}},
    {"LockDoors", {PERSISTENT, BOOL, "1", "0", 0}},
    {"LockDoorsTimer", {PERSISTENT, INT, "0", "0", 0}},
    {"LongCancelButtonControl", {PERSISTENT, INT, "5", "0", 2, SETTINGS_SIMPLE}},
    {"LongDistanceButtonControl", {PERSISTENT, INT, "5", "0", 2, SETTINGS_SIMPLE}},
    {"LongModeButtonControl", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"LongStarButtonControl", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"LongitudinalActuatorDelay", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"LongitudinalActuatorDelayStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"LateralManeuverStatus", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON, "{}", "{}"}},
    {"LongitudinalManeuverPaddleMode", {PERSISTENT, STRING, "auto", "auto"}},
    {"LongitudinalManeuverStatus", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON, "{}", "{}"}},
    {"LongitudinalTune", {PERSISTENT, BOOL, "1", "0", 0, SETTINGS_SIMPLE}},
    {"LoudBlindspotAlert", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"LoudBlindspotAlertWhenDisengaged", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"LowVoltageShutdown", {PERSISTENT, FLOAT, "11.8", "11.8", 3, SETTINGS_SIMPLE}},
    {"MainCruiseButtonControl", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ManualUpdateInitiated", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"AMapKey1", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"AMapKey2", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"ApiCache_NavDestinations", {PERSISTENT, JSON, "[]", "[]"}},
    {"FavoriteDestinations", {PERSISTENT, JSON, "[]", "[]"}},
    {"MapAcceleration", {PERSISTENT, BOOL, "0", "0", 1}},
    {"MapboxPublicKey", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"MapBoxRequests", {PERSISTENT, JSON, "{}", "{}"}},
    {"MapboxSecretKey", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"MapDeceleration", {PERSISTENT, BOOL, "0", "0", 1}},
    {"MapdSettings", {PERSISTENT, JSON, "{}", "{}"}},
    {"MapGears", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"MapsSelected", {PERSISTENT, STRING, "", "", 0}},
    {"MapSpeedLimit", {CLEAR_ON_MANAGER_START, FLOAT, "0.0", "0.0"}},
    {"NavDesiresAllowed", {PERSISTENT, BOOL, "1", "0", 2}},
    {"NavLanePositioningAllowed", {PERSISTENT, BOOL, "0", "0", 2}},
    {"NavLongitudinalAllowed", {PERSISTENT, BOOL, "1", "0", 2}},
    {"ClearNavOnOffroad", {PERSISTENT, BOOL, "1", "1", 2, SETTINGS_SIMPLE}},
    {"ClearNavOnOffroadTimeoutMinutes", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"NavDestination", {PERSISTENT | CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"NavInstructionCollapsed", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0", "0"}},
    {"NavInstructionState", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON, "{}", "{}"}},
    {"NextMapSpeedLimit", {CLEAR_ON_MANAGER_START, JSON, "{}", "{}"}},
    {"VisionSpeedLimit", {CLEAR_ON_MANAGER_START, FLOAT, "0.0", "0.0"}},
    {"VisionSpeedLimitConfidence", {CLEAR_ON_MANAGER_START, FLOAT, "0.0", "0.0"}},
    {"VisionSpeedLimitBookmarkCount", {CLEAR_ON_MANAGER_START, INT, "0", "0"}},
    {"VisionSpeedLimitDebugSession", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"VisionSpeedLimitLastEvent", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"VisionSpeedLimitStatus", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"VisionSpeedLimitStream", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"VisionSpeedLimitSupportCount", {CLEAR_ON_MANAGER_START, INT, "0", "0"}},
    {"VisionSpeedLimitSupportSpeed", {CLEAR_ON_MANAGER_START, FLOAT, "0.0", "0.0"}},
    {"MaxDesiredAcceleration", {PERSISTENT, FLOAT, "4.0", "2.0", 2}},
    {"MinimumBackupSize", {PERSISTENT, INT, "0", "0"}},
    {"MinimumLaneChangeSpeed", {PERSISTENT, FLOAT, "20.0", "20.0", 2, SETTINGS_SIMPLE}},
    {"ModeButtonControl", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ModelDownloadProgress", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"ModelDrivesAndScores", {PERSISTENT, JSON, "{}", "{}"}},
    {"ModelReleasedDates", {PERSISTENT, STRING, "", "", 1}},
    {"ModelRandomizer", {PERSISTENT, BOOL, "0", "0", 2}},
    {"LatSmoothSeconds", {PERSISTENT, FLOAT, "0.1", "0.1", 3}},
    {"LongSmoothSeconds", {PERSISTENT, FLOAT, "0.3", "0.3", 3}},
    {"ModelSortMode", {PERSISTENT, STRING, "alphabetical", "alphabetical", 1}},
    {"ModelToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"ModelUI", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"ModelVersions", {PERSISTENT, STRING, "", "", 1}},
    {"ModelManifestVersion", {PERSISTENT, STRING, "", "", 1}},
    {"NavigationUI", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"NNFF", {PERSISTENT, BOOL, "0", "0", 2}},
    {"NNFFLite", {PERSISTENT, BOOL, "0", "0", 2}},
    {"NostalgiaMode", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"NNFFModelName", {CLEAR_ON_MANAGER_START, STRING, "", "", 0}},
    {"NoLogging", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"NoUploads", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"NudgelessLaneChange", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"NudgelessLaneChangeOnlyWhenEngaged", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"NumericalTemp", {PERSISTENT, BOOL, "0", "0", 3}},
    {"Offset1", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset2", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset3", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset4", {PERSISTENT, FLOAT, "5.0", "0.0", 0}},
    {"Offset5", {PERSISTENT, FLOAT, "10.0", "0.0", 0}},
    {"Offset6", {PERSISTENT, FLOAT, "10.0", "0.0", 0}},
    {"Offset7", {PERSISTENT, FLOAT, "10.0", "0.0", 0}},
    {"OneLaneChange", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"OnroadDistanceButton", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"OnroadDistanceButtonPressed", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"FavoriteVirtualAccelCruiseCounter", {CLEAR_ON_MANAGER_START, INT, "0", "0"}},
    {"FavoriteVirtualDecelCruiseCounter", {CLEAR_ON_MANAGER_START, INT, "0", "0"}},
    {"FavoriteTrafficModeCounter", {CLEAR_ON_MANAGER_START, INT, "0", "0"}},
    {"WheelButtonBookmarkCounter", {CLEAR_ON_MANAGER_START, INT, "0", "0"}},
    {"openpilotMinutes", {PERSISTENT, INT, "0", "0", 0}},
    {"OverpassRequests", {PERSISTENT, JSON, "{}", "{}"}},
    {"PathColor", {PERSISTENT, STRING, "", "", 2, SETTINGS_SIMPLE}},
    {"PathEdgesColor", {PERSISTENT, STRING, "", "", 2, SETTINGS_SIMPLE}},
    {"PathEdgeWidth", {PERSISTENT, FLOAT, "20.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"PathWidth", {PERSISTENT, FLOAT, "6.1", "5.9", 2, SETTINGS_SIMPLE}},
    {"PauseAOLOnBrake", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"PauseLateralOnSignal", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"PauseLateralSpeed", {PERSISTENT, FLOAT, "0.0", "0.0", 1, SETTINGS_SIMPLE}},
    {"LateralResumeDelay", {PERSISTENT, FLOAT, "0.0", "0.0", 1, SETTINGS_SIMPLE}},
    {"PedalsOnUI", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"PIPPreviewEnabled", {PERSISTENT, BOOL, "0", "0", 1}},
    {"PIPPreviewMask", {PERSISTENT, JSON, "{\"width\":1928,\"height\":1208,\"center_left\":[315,548],\"center_right\":[1571,539],\"crop_size\":580}", "{\"width\":1928,\"height\":1208,\"center_left\":[315,548],\"center_right\":[1571,539],\"crop_size\":580}", 2}},
    {"PIPPreviewShowOnBlinker", {PERSISTENT, BOOL, "0", "0", 1}},
    {"PIPPreviewShowOnBSM", {PERSISTENT, BOOL, "0", "0", 1}},
    {"PIPPreviewInvert", {PERSISTENT, BOOL, "0", "0", 1}},
    {"GalaxyPaired", {PERSISTENT, BOOL, "0", "0", 0}},
    {"GalaxyUploadPending", {PERSISTENT, BOOL, "0", "0", 0}},
    {"PreferredSchedule", {PERSISTENT, INT, "2", "0", 0}},
    {"PreviousSpeedLimit", {PERSISTENT, FLOAT, "0.0", "0.0"}},
    {"PromptDistractedVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"PromptVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"PulseGlideSpeedDelta", {PERSISTENT, FLOAT, "5.0", "5.0", 3}},
    {"QOLLateral", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"QOLLongitudinal", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"QOLVisuals", {PERSISTENT, BOOL, "1", "0", 0, SETTINGS_SIMPLE}},
    {"RadarTakeoffs", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"RadarTracksUI", {PERSISTENT, BOOL, "0", "0", 3}},
    {"RainbowPath", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"RandomEvents", {PERSISTENT, BOOL, "0", "0", 1}},
    {"RandomThemes", {PERSISTENT, BOOL, "0", "0", 1}},
    {"RandomThemesHolidays", {PERSISTENT, BOOL, "0", "0", 1}},
    {"ReduceAccelerationLowVisibility", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ReduceAccelerationRain", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ReduceAccelerationRainStorm", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ReduceAccelerationSnow", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ReduceLateralAccelerationLowVisibility", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ReduceLateralAccelerationRain", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ReduceLateralAccelerationRainStorm", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ReduceLateralAccelerationSnow", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"RefuseVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"RelaxedFollow", {PERSISTENT, FLOAT, "1.6", "1.6", 2}},
    {"RelaxedFollowHigh", {PERSISTENT, FLOAT, "1.4", "1.4", 2}},
    {"RelaxedJerkAcceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkDeceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkSpeed", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RelaxedJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"RivianAngleControl", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"RivianAngleSaturated", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL, "0", "0"}},
    {"RivianToiRecoveryFailed", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL, "0", "0"}},
    {"RecoveryPower", {PERSISTENT, FLOAT, "1.0", "1.0", 2}},
    {"RoadEdgesWidth", {PERSISTENT, FLOAT, "2.0", "2.0", 2, SETTINGS_SIMPLE}},
    {"RoadNameUI", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"RotatingWheel", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"ScreenBrightness", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"ScreenBrightnessOnroad", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"ScreenManagement", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"ScreenRecorder", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"ScreenTimeout", {PERSISTENT, INT, "30", "30", 2, SETTINGS_SIMPLE}},
    {"ScreenTimeoutOnroad", {PERSISTENT, INT, "30", "10", 2, SETTINGS_SIMPLE}},
    {"SecOCKeys", {PERSISTENT | DONT_LOG, STRING, "", "", 0}},
    {"SafeMode", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SafeModeBackup", {PERSISTENT, JSON, "{}", "{}"}},
    {"SetSpeedLimit", {PERSISTENT, BOOL, "0", "0", 1}},
    {"SetSpeedOffset", {PERSISTENT, FLOAT, "0.0", "0.0", 2, SETTINGS_SIMPLE}},
    {"ShowCEMStatus", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"ShowCCMStatus", {PERSISTENT, BOOL, "0", "0", 2}},
    {"ShowCPU", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowCSCStatus", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"ShowGPU", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowIP", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowMemoryUsage", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowModeStatusBanner", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"ShownToggleDescriptions", {PERSISTENT, JSON, "{}", "{}"}},
    {"ShowSLCOffset", {PERSISTENT, BOOL, "1", "0", 0}},
    {"ShowSpeedLimits", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"ShowSteering", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowStoppingPoint", {PERSISTENT, BOOL, "1", "0", 3}},
    {"ShowStoppingPointMetrics", {PERSISTENT, BOOL, "1", "0", 3}},
    {"ShowStorageLeft", {PERSISTENT, BOOL, "0", "0", 3}},
    {"ShowStorageUsed", {PERSISTENT, BOOL, "0", "0", 3}},
    {"SidebarMetrics", {PERSISTENT, BOOL, "0", "0", 3}},
    {"SidebarOpen", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SignalAnimation", {PERSISTENT, STRING, "stock", "stock", 0}},
    {"SignalMetrics", {PERSISTENT, BOOL, "0", "0", 3}},
    {"SignalToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"SimpleMode", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"SLCAbbreviatedSources", {PERSISTENT, BOOL, "0", "0", 3}},
    {"SLCActiveSourcesOnly", {PERSISTENT, BOOL, "0", "0", 3}},
    {"SLCConfirmation", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SLCConfirmationHigher", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SLCConfirmationLower", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SLCFallback", {PERSISTENT, INT, "2", "0", 1}},
    {"SLCLookaheadHigher", {PERSISTENT, INT, "0", "0", 2}},
    {"SLCLookaheadLower", {PERSISTENT, INT, "0", "0", 2}},
    {"SLCMapboxFiller", {PERSISTENT, BOOL, "1", "0", 1, SETTINGS_SIMPLE}},
    {"SLCOverride", {PERSISTENT, INT, "1", "0", 1}},
    {"SLCPriority", {PERSISTENT, STRING, "", "", 2}},
    {"SLCPriority1", {PERSISTENT, STRING, "Vision", "Map Data", 2}},
    {"SLCPriority2", {PERSISTENT, STRING, "Map Data", "Dashboard", 2}},
    {"SNGHack", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"SoundPack", {PERSISTENT, STRING, "stock", "stock", 0}},
    {"SoundToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"SLCAdoptSpeedLimit", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"SLCForceCruiseSpeed", {CLEAR_ON_MANAGER_START, FLOAT, "0.0", "0.0"}},
    {"SpeedLimitAccepted", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"SpeedLimitChangedAlert", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"SpeedLimitController", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SpeedLimitFiller", {PERSISTENT, BOOL, "0", "0", 0}},
    {"SpeedLimits", {PERSISTENT | DONT_LOG, JSON, "[]", "[]"}},
    {"SpeedLimitsFiltered", {PERSISTENT | DONT_LOG, JSON, "[]", "[]"}},
    {"SpeedLimitSources", {PERSISTENT, BOOL, "0", "0", 3}},
    {"VisionSpeedLimitAutoBookmark", {PERSISTENT, BOOL, "0", "0", 0}},
    {"VisionSpeedLimitAutoPreserveSegment", {PERSISTENT, BOOL, "0", "0", 0}},
    {"VisionSpeedLimitDetection", {PERSISTENT, BOOL, "1", "0", 0}},
    {"VisionSpeedLimitLowLimitFilter", {PERSISTENT, BOOL, "0", "0", 0}},
    {"VisionSpeedLimitLowLimitThreshold", {PERSISTENT, INT, "25", "25", 0}},
    {"VisionSpeedLimitTrainingCollector", {PERSISTENT, BOOL, "1", "1", 0}},
    {"StandardFollow", {PERSISTENT, FLOAT, "1.45", "1.45", 2}},
    {"StandardFollowHigh", {PERSISTENT, FLOAT, "1.2", "1.2", 2}},
    {"StandardJerkAcceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkDeceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkSpeed", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandardJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"StandbyMode", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"StartAccel", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StartAccelStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StartupMessageBottom", {PERSISTENT, STRING, "Always keep hands on wheel and eyes on road", "Always keep hands on wheel and eyes on road", 0}},
    {"StartupMessageTop", {PERSISTENT, STRING, "Be ready to take over at any time", "Be ready to take over at any time", 0}},
    {"StaticPedalsOnUI", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"SteerDelay", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerDelayModeMigrated", {PERSISTENT, BOOL}},
    {"SteerDelayStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerFriction", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerFrictionStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerKP", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerKPStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerLatAccel", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerLatAccelStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerOffset", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerOffsetStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerRatio", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"SteerRatioStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"EnableTorqueBarWidget", {PERSISTENT, BOOL, "1", "0", 0}},
    {"StockConfidenceBallWidget", {PERSISTENT, BOOL, "0", "0", 0, SETTINGS_SIMPLE}},
    {"StockDongleId", {PERSISTENT, STRING, "", ""}},
    {"StopAccel", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StopAccelStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StoppedTimer", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"StoppingDecelRate", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StoppingDecelRateStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"StarButtonControl", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"SwitchbackModeCooldown", {PERSISTENT, INT, "5", "0", 2, SETTINGS_SIMPLE}},
    {"SwitchbackModeEnabled", {CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0", "0"}},
    {"SubaruSNG", {PERSISTENT, BOOL, "1", "0", 2, SETTINGS_SIMPLE}},
    {"SubaruSNGManualParkingBrake", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"SubaruStopStartOff", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"TacoTune", {PERSISTENT, BOOL, "0", "0", 2}},
    {"TeslaCoopSteering", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"TestAlert", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"TetheringEnabled", {PERSISTENT, INT, "0", "0", 0}},
    {"ThemeDownloadProgress", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"ThemesDownloaded", {PERSISTENT, JSON, "{}", "{}"}},
    {"Timezone", {PERSISTENT, STRING, "", ""}},
    {"TinygradUpdateAvailable", {PERSISTENT, BOOL, "0", "0", 1}},
    {"ToyotaDoors", {PERSISTENT, BOOL, "1", "0", 0}},
    {"TrailerLoad", {PERSISTENT, INT, "0", "0", 2}},
    {"TrafficFollow", {PERSISTENT, FLOAT, "0.75", "0.75", 2}},
    {"TrafficJerkAcceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"TrafficJerkDanger", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"TrafficJerkDeceleration", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"TrafficJerkSpeed", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"TrafficJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0", "100.0", 3}},
    {"TruckTuning", {PERSISTENT, BOOL, "0", "0", 3}},
    {"TuningLevel", {PERSISTENT, INT, "0", "0", 0}},
    {"TuningLevelConfirmed", {PERSISTENT, BOOL, "0", "0", 0}},
    {"TurnDesires", {PERSISTENT, BOOL, "0", "0", 2}},
    {"TurnSteeringLimitMuteSpeed", {PERSISTENT, INT, "0", "0", 0}},
    {"UnlockDoors", {PERSISTENT, BOOL, "1", "0", 0}},
    {"Updated", {PERSISTENT, STRING, "0", "0"}},
    {"UpdateSpeedLimits", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UpdateSpeedLimitsStatus", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
    {"UpdateTinygrad", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UpdateWheelImage", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UseActiveTheme", {CLEAR_ON_MANAGER_START, BOOL, "0", "0"}},
    {"UseAutoSteerDelay", {PERSISTENT, BOOL, "1", "1", 3}},
    {"UseKonikServer", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"UseSI", {PERSISTENT, BOOL, "1", "1", 3}},
    {"UserFavorites", {PERSISTENT, STRING, "", "", 1}},
    {"UseVienna", {PERSISTENT, BOOL, "0", "0", 1, SETTINGS_SIMPLE}},
    {"VASMAnnotationConfig", {PERSISTENT, JSON, "{}", "{}", 2}},
    {"VASMConfidenceThreshold", {PERSISTENT, FLOAT, "0.94", "0.94", 2}},
    {"VASMEnabled", {PERSISTENT, BOOL, "0", "0", 1}},
    {"VASMLeftActive", {CLEAR_ON_MANAGER_START, STRING, "0", "0", 2}},
    {"VASMLeftConfidence", {CLEAR_ON_MANAGER_START, STRING, "0.0", "0.0", 2}},
    {"VASMLastUpdateMonoTime", {CLEAR_ON_MANAGER_START, STRING, "0", "0", 2}},
    {"VASMRightActive", {CLEAR_ON_MANAGER_START, STRING, "0", "0", 2}},
    {"VASMRightConfidence", {CLEAR_ON_MANAGER_START, STRING, "0.0", "0.0", 2}},
    {"VASMSmoothSeconds", {PERSISTENT, FLOAT, "0.2", "0.2", 2}},
    {"VASMTimestampEof", {CLEAR_ON_MANAGER_START, STRING, "0", "0", 2}},
    {"VEgoStarting", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VEgoStartingStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VEgoStopping", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VEgoStoppingStock", {PERSISTENT, FLOAT, "0.0", "0.0", 3}},
    {"VeryLongCancelButtonControl", {PERSISTENT, INT, "6", "0", 2, SETTINGS_SIMPLE}},
    {"VeryLongDistanceButtonControl", {PERSISTENT, INT, "6", "0", 2, SETTINGS_SIMPLE}},
    {"VeryLongModeButtonControl", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"VeryLongStarButtonControl", {PERSISTENT, INT, "0", "0", 2, SETTINGS_SIMPLE}},
    {"VoltSNG", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"JeepBrakeHold", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"GMAutoHold", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"VoltOnePedalMode", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"ToyotaAutoHold", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"WarningImmediateVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"WarningSoftVolume", {PERSISTENT, INT, "101", "101", 2, SETTINGS_SIMPLE}},
    {"WeatherPresets", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"WeatherToken", {PERSISTENT | DONT_LOG, STRING, "", "", 2}},
    {"WheelControls", {PERSISTENT, STRING, "", "", 2}},
    {"WheelIcon", {PERSISTENT, STRING, "stock", "stock", 0}},
    {"WheelSpeed", {PERSISTENT, BOOL, "0", "0", 2, SETTINGS_SIMPLE}},
    {"WheelToDownload", {CLEAR_ON_MANAGER_START, STRING, "", ""}},
};
